### ISSUE TITLE
Correcciones y sugerencias

### ISSUE THREAD

**Issue by flbulgarelli** [MatiMon/QueMePongo#1]
¡Buenas!

Antes que nada, una aclaración sobre este comentario: 

> El enunciado se contradice con el requerimiento de la iteración anterior que solicita que no se puedan crear prendas sin tipo, material o color; pero para poder cumplir con el 2do y 3er requerimiento de esta entrega se agregaron un constructor que recibe únicamente el tipoPrenda y los setters de material y colorPrimario. Normalmente deberíamos clarificar con el analista funcional.

En realidad no son requerimientos contractorios sino complementarios: una `Prenda` final, es decir, una vez completamente configurada, va a tener que tener tipo, color y material, sin excepción. Pero de lo que habla el requerimiento (_Como usuarie de QuéMePongo, quiero crear una prenda especificando **primero** de qué tipo es._, las negritas son mías) es del orden en que estos datos se especifican durante el proceso de construcción. En otras palabras, mientras que el requerimiento de QMP1 habla del tiempo **de ejecución** (cómo se comporta el sistema normalmente) y el otro del tiempo de creación (cómo se llegan a crear los objetos que luego el sistema utilizará). 

Dicho eso, te dejo nuestros comentarios: 

1. Un detalle sobre el diagrama: el color secundario es opcional, pero no múltiple. Vos marcaste en el diagrama por sobre su flecha una cardinalidad `0..*` (que indica que es un colección), pero en realidad es `0..1`. 
2. Otro detalle: acá te faltó setear el atributo https://github.com/MatiMon/QueMePongo/blob/3f3ac9b33216fb588ede2ad41a348bbf7c74a700/src/main/java/TipoPrenda.java#L10-L14 
3. Acá ... https://github.com/MatiMon/QueMePongo/blob/3f3ac9b33216fb588ede2ad41a348bbf7c74a700/src/main/java/Atuendo.java#L8-L14 ... hay dos cuestiones para atender: 
   1. Estás rompiendo el encapsulamiento de cada una de las partes (prendas). Más que hacer `parteSuperior.tipoPrenda.categoria == Categoria.SUPERIOR` podrías hacer `parteSuperior.esDeCategoria(Categoria.SUPERIOR)` o incluso `parteSuperior.esSuperior()`
   2. Estás haciendo una validación de múltiples parámetros en una misma expresión, lo que hace que si alguna de ellas falla, se lanzará una excepción, pero no sabrás cual fue el verdadero motivo de la falla (¿quien estaba mal configurado? ¿la parte superor? ¿la inferior? ¿ambas?). Por ese motivo lo idea es que escribas tres validaciones diferentes, independientes, línea a línea. 
 4. Ojo, acá ... https://github.com/MatiMon/QueMePongo/blob/3f3ac9b33216fb588ede2ad41a348bbf7c74a700/src/main/java/Atuendo.java#L17-L19  ... estás haciendo que un atuendo pueda pertenecer a una única institución (¿y si más de una usa el mismo atuendo? ¿Y si más adelante tenemos atuendos no asociados a instituciones?). Si bien esto es discutible, debería hacernos ruido, porque lo único que sabemos a ciencia cierta es lo recíproco (_Como administrador de QueMePongo, quiero poder configurar diferentes uniformes para distintas instituciones_): cada institución tiene un uniforme. 
 5. También hablando del mismo método: al exponer este setter estás haciendo mutable al atuendo, cuando quizás esto no era necesario. En general, vamos a intentar minimizar la mutabilidad de los objetos. 
 6. Cuestión de código: acá ... https://github.com/MatiMon/QueMePongo/blob/3f3ac9b33216fb588ede2ad41a348bbf7c74a700/src/main/java/Borrador.java#L8-L11 ... no es necesaria la variable local. Podés retornar directamente y el método te queda más breve. 
 7. Un problema en la clase `Borrador` (que de hecho le resta utilidad) es que aunque permite especificar por un lado el tipo, el material y demás, el `crearPrenda` toma todos los atributos. Esto tiene dos consecuencias negativas: 
    1.  Si tuvieras muchos otros aspectos para configurar, este método crecería y crecería en cantidad de parámetros
    2.  No se puede configurar cada aspecto por partes. 
   Tanto por este motivo como el anterior,  el patrón builder en general se implementa de forma tal que cada aspecto que querés configurar sea un método independiente, como `setMaterial`, `setTrama` (o tamién `configurarMaterial`/ `cargarMaterial`/etc) y así, y luego un método `crear` que no tome parámetros. 

¡Saludos!

**Comment by flbulgarelli** [comment]
PD1: los comentarios anteriores también aplican a éste código: https://github.com/MatiMon/QueMePongo/blob/3f3ac9b33216fb588ede2ad41a348bbf7c74a700/src/main/java/Prenda.java#L10-L15

PD2: Nunca tipes en Java a las listas como `ArrayList`, usá en su lugar una interfaz más flexible como `List`: https://github.com/MatiMon/QueMePongo/blob/3f3ac9b33216fb588ede2ad41a348bbf7c74a700/src/main/java/ConfiguradorUniformes.java#L4

**Comment by MatiMon** [comment]
¡Buenas noches Franco!

Perdón la demora en contestar pero entre la entrega del TPA, las lecturas, el ejercicio de la clase de hoy y otras cosas no tuve tiempo de ponerme a hacer las correcciones y escribir una respuesta a la altura de tus comentarios.

1 y 2. ¡Tenes razón! Ambas fueron distracciones.
3. Es verdad, después de la lectura de los apuntes de Code Smells y la clase de hoy lo veo mucho más claro.
La repetición de la estructura en las 3 validaciones de la categoría (las 3 son básicamente un if con un esCategoria() == categoria) ¿la asumimos por lo que me comentabas de poder detectar con precisión cuál fue el error si falla alguna, no?
Lo que sigue haciendome ruido es lo de delegar esas 3 validaciones en otra función para evitar la repitición de código, acá:
>
https://github.com/MatiMon/QueMePongo/blob/132c35a5e8821a349eadc8f846078d93f79590fd/src/main/java/Atuendo.java#L18-L22
pero calculo que debe ser porque no tengo la visión "macro" de un proyecto grande, por lo que confío en ustedes.

4. Esto implica crear la abstracción Institucion y que únicamente tenga un atuendo. Ya que en principio no tendría comportamiento ¿puedo modelarla como clase abstracta?
5. Got it. En función del 4 corrijo eso.
6. Una burrada lisa y llanamente. Perdón por eso jajajaja.
7. 8 y 9. Creo que esto fue un error de concepto mío. Pensaba en cómo el Borrador iba a saber con qué atributos crear la Prenda si no los recibía por parámetro en ese método cuando justamente la idea es desentendernos de eso y permitirlo con los setters.

¡Gracias por tu respuesta tan detallada Franco!

Saludos.

**Comment by flbulgarelli** [comment]
¡Hola!

No sé si entendí muy bien este comentario: 

> Lo que sigue haciendome ruido es lo de delegar esas 3 validaciones en otra función para evitar la repitición de código, acá:

Si bien delegar en general es una buena idea, no le veo mucho sentido a delegar un comportamiento que se va a ejecutar únicamente a partir del constructor, porque por definición no se puede reutilizar (porque hay un sólo constructor base normalmente y porque si eso se garantizó en la construcción y los atributos asociados no mutan, entonces si una vez la validación pasó, así sucederá siempre). Por eso es que en general no recomiendo hacer un método de "validaciones que se llamarán desde el constructor". Por el contrario, si ese código queda excesivamente largo sin delegar, más bien valdrá la pena preguntarse si parte de ese comportamiento no puede delegarse en los objetos inyectados (lo que demás lo haría reusable), o incluso, si toda esa lógica creacional no convendría llevarla a objetos creacionales (como un builder).. 


Sobre esto: 

> Esto implica crear la abstracción Institucion y que únicamente tenga un atuendo. Ya que en principio no tendría comportamiento ¿puedo modelarla como clase abstracta?

Ojo, lo que la hace abstracta es la imposibilidad de instanciarla, no la falta de comportamiento. Debería ser una clase concreta. .

**Comment by MatiMon** [comment]
Respecto al primer comentario quise hacer una analogía con el ejemplo que vimos en clase pero no tuve en cuenta que acá estaba en un constructor.

¡Gracias Fran! 

Buen inicio de semana.
